package com.kingagroot.kingdraw.config;

public class APIConfig
{
    public static final String ABOUT;
    public static final String ADDFILE;
    public static final String AI_UPLOAD = "http://image.recognition.kingdraw.cn/Home/Upload";
    public static final String API_BK_HOME;
    public static final String API_BK_LIST;
    private static final String API_URL;
    public static final String CAS_SEARCH;
    public static final String CHECK_LOGIN_NAME;
    public static final String CHECK_VERSION_IS_NOT_AVAILABLE;
    public static final String CONFIG;
    public static final String CONFIG_TYPE;
    public static final String CURRENT_USER;
    public static final String DELETEFILE;
    public static final String DELETEMULTI;
    public static final String DISCLAIMER_CN;
    public static final String DISCLAIMER_EN;
    public static final String DOWNLOADFILE;
    public static final String ECODE_SMS;
    public static final String ECODE_SMS_KEY;
    public static final String EDIT_FILE;
    public static final String ERROR_LOG;
    public static final String FIND_PASSWORD;
    public static final String FOLDERFILELIST;
    public static final String FORMAT_EN;
    public static final String FORMAT_ZH;
    public static final String GETALLCHECKEDWITHOUT;
    public static final String GETBYFILENAME;
    public static final String GETLIST;
    public static final String GETQQGROUP;
    public static final String GETUNREADCOUNT;
    public static final String GET_OPTION_DETAIL_BY_ID;
    public static final String GET_OPTION_LIST;
    public static final String GSGROUPLIST;
    public static final String GUIDEPPTLIST;
    public static final String HELP_EN;
    public static final String HELP_ZH;
    public static final String INSTRUCTIONS;
    private static final String IP_BAIKE;
    private static final String KINGDRAW_DOC;
    public static final String LOGIN;
    public static final String LOGOFF;
    public static final String MobileLog;
    private static final String NEW_IP_URL;
    public static final String NEW_VERSION_EN;
    public static final String NEW_VERSION_ZH;
    public static final String NOTICEWEB;
    private static final String OCR_URL;
    public static final String OPTION;
    public static final String READ_ALL;
    public static final String REGISTER;
    public static final String RENAME;
    public static final String RENAMEADD;
    public static final String SHARE;
    public static final String UNDECODE_SMS;
    public static final String UPDATE;
    public static final String UPDATE_INFO;
    public static final String UPDATE_PASSWORD;
    public static final String UPLOAD_APP_UNRECOGNISED_IMAGE;
    public static final String URGENTTIP;
    public static final String USER_XIEYI;
    public static final String WEBVIEW_CONTENT;
    public static String WORK_URL;
    public static final String XIEYILOGOFF;
    public static final String YINSI_XIEYI;
    public static final String getWhiteList;
    
    static {
        if (AppConfig.RELEASE == Release.STANDARD) {
            final StringBuilder sb = new StringBuilder();
            sb.append("http://");
            sb.append("v2.service.kingdraw.cn");
            OCR_URL = (API_URL = sb.toString());
            IP_BAIKE = "https://baike.kingdraw.com";
            NEW_IP_URL = "http://wk-api.kingdraw.com";
            APIConfig.WORK_URL = "http://wk.kingdraw.com/";
        }
        else {
            final StringBuilder sb2 = new StringBuilder();
            sb2.append("http://");
            sb2.append("172.16.70.22");
            sb2.append(":");
            sb2.append("11001");
            final String ocr_URL = API_URL = sb2.toString();
            IP_BAIKE = "http://47.105.182.188:11111";
            NEW_IP_URL = "http://172.16.70.28:5600";
            OCR_URL = ocr_URL;
            APIConfig.WORK_URL = "http://172.16.70.28:8100/";
        }
        KINGDRAW_DOC = "https://doc.kingdraw.com";
        final StringBuilder sb3 = new StringBuilder();
        sb3.append(APIConfig.API_URL);
        sb3.append("/Service/Update/Index");
        UPDATE = sb3.toString();
        final StringBuilder sb4 = new StringBuilder();
        sb4.append(APIConfig.API_URL);
        sb4.append("/Service/Option/Index");
        OPTION = sb4.toString();
        final StringBuilder sb5 = new StringBuilder();
        sb5.append(APIConfig.API_URL);
        sb5.append("/Service/Option/GetOptionList");
        GET_OPTION_LIST = sb5.toString();
        final StringBuilder sb6 = new StringBuilder();
        sb6.append(APIConfig.API_URL);
        sb6.append("/Service/Option/GetOptionDetailById");
        GET_OPTION_DETAIL_BY_ID = sb6.toString();
        final StringBuilder sb7 = new StringBuilder();
        sb7.append(APIConfig.API_URL);
        sb7.append("/Service/User/UpdatePassword");
        UPDATE_PASSWORD = sb7.toString();
        final StringBuilder sb8 = new StringBuilder();
        sb8.append(APIConfig.API_URL);
        sb8.append("/Service/Content/WebView?title=\u5173\u4e8e\u6211\u4eec");
        ABOUT = sb8.toString();
        final StringBuilder sb9 = new StringBuilder();
        sb9.append(APIConfig.API_URL);
        sb9.append("/Service/ErrorLog/Index");
        ERROR_LOG = sb9.toString();
        final StringBuilder sb10 = new StringBuilder();
        sb10.append(APIConfig.API_URL);
        sb10.append("/Service/MobileLog/Index");
        MobileLog = sb10.toString();
        final StringBuilder sb11 = new StringBuilder();
        sb11.append(APIConfig.API_URL);
        sb11.append("/Service/User/SendSms");
        UNDECODE_SMS = sb11.toString();
        final StringBuilder sb12 = new StringBuilder();
        sb12.append(APIConfig.API_URL);
        sb12.append("/Service/User/RegistSendSms");
        ECODE_SMS = sb12.toString();
        final StringBuilder sb13 = new StringBuilder();
        sb13.append(APIConfig.API_URL);
        sb13.append("/Service/User/RegistSendSmsKey");
        ECODE_SMS_KEY = sb13.toString();
        final StringBuilder sb14 = new StringBuilder();
        sb14.append(APIConfig.API_URL);
        sb14.append("/Service/User/CheckLoginName");
        CHECK_LOGIN_NAME = sb14.toString();
        final StringBuilder sb15 = new StringBuilder();
        sb15.append(APIConfig.API_URL);
        sb15.append("/Service/User/FindPassword");
        FIND_PASSWORD = sb15.toString();
        final StringBuilder sb16 = new StringBuilder();
        sb16.append(APIConfig.API_URL);
        sb16.append("/Service/User/Register");
        REGISTER = sb16.toString();
        final StringBuilder sb17 = new StringBuilder();
        sb17.append(APIConfig.API_URL);
        sb17.append("/Service/User/Login");
        LOGIN = sb17.toString();
        final StringBuilder sb18 = new StringBuilder();
        sb18.append(APIConfig.API_URL);
        sb18.append("/Service/User/CurrentUser");
        CURRENT_USER = sb18.toString();
        final StringBuilder sb19 = new StringBuilder();
        sb19.append(APIConfig.API_URL);
        sb19.append("/Service/User/UpdateInfo");
        UPDATE_INFO = sb19.toString();
        final StringBuilder sb20 = new StringBuilder();
        sb20.append(APIConfig.API_URL);
        sb20.append("/Service/Content/WebView");
        USER_XIEYI = sb20.toString();
        final StringBuilder sb21 = new StringBuilder();
        sb21.append(APIConfig.API_URL);
        sb21.append("/Service/Content/WebView?title=\u4f7f\u7528\u8bf4\u660e");
        INSTRUCTIONS = sb21.toString();
        final StringBuilder sb22 = new StringBuilder();
        sb22.append(APIConfig.API_URL);
        sb22.append("/Service/Content/WebView");
        YINSI_XIEYI = sb22.toString();
        final StringBuilder sb23 = new StringBuilder();
        sb23.append(APIConfig.KINGDRAW_DOC);
        sb23.append("/KingdrawPrivacy_2.3.0/disclaimer.html");
        DISCLAIMER_CN = sb23.toString();
        final StringBuilder sb24 = new StringBuilder();
        sb24.append(APIConfig.KINGDRAW_DOC);
        sb24.append("/KingdrawPrivacy_2.3.0/disclaimer_en.html");
        DISCLAIMER_EN = sb24.toString();
        final StringBuilder sb25 = new StringBuilder();
        sb25.append(APIConfig.API_URL);
        sb25.append("/Service/Content/WebView");
        WEBVIEW_CONTENT = sb25.toString();
        final StringBuilder sb26 = new StringBuilder();
        sb26.append(APIConfig.API_URL);
        sb26.append("/Service/Config/List");
        CONFIG_TYPE = sb26.toString();
        final StringBuilder sb27 = new StringBuilder();
        sb27.append(APIConfig.API_URL);
        sb27.append("/Service/FolderFile/List");
        FOLDERFILELIST = sb27.toString();
        final StringBuilder sb28 = new StringBuilder();
        sb28.append(APIConfig.API_URL);
        sb28.append("/Util/ViewFile");
        DOWNLOADFILE = sb28.toString();
        final StringBuilder sb29 = new StringBuilder();
        sb29.append(APIConfig.API_URL);
        sb29.append("/Service/FolderFile/Add");
        ADDFILE = sb29.toString();
        final StringBuilder sb30 = new StringBuilder();
        sb30.append(APIConfig.API_URL);
        sb30.append("/Service/FolderFile/Delete");
        DELETEFILE = sb30.toString();
        final StringBuilder sb31 = new StringBuilder();
        sb31.append(APIConfig.API_URL);
        sb31.append("/Service/FolderFile/Edit");
        EDIT_FILE = sb31.toString();
        final StringBuilder sb32 = new StringBuilder();
        sb32.append(APIConfig.API_URL);
        sb32.append("/Service/FolderFile/GetByFileName");
        GETBYFILENAME = sb32.toString();
        final StringBuilder sb33 = new StringBuilder();
        sb33.append(APIConfig.API_URL);
        sb33.append("/Service/FolderFile/ReName");
        RENAME = sb33.toString();
        final StringBuilder sb34 = new StringBuilder();
        sb34.append(APIConfig.API_URL);
        sb34.append("/Service/UrgentTip/WebView");
        URGENTTIP = sb34.toString();
        final StringBuilder sb35 = new StringBuilder();
        sb35.append(APIConfig.API_URL);
        sb35.append("/Service/Config/List");
        CONFIG = sb35.toString();
        final StringBuilder sb36 = new StringBuilder();
        sb36.append(APIConfig.API_URL);
        sb36.append("/Service/Config/GetQqGroup");
        GETQQGROUP = sb36.toString();
        final StringBuilder sb37 = new StringBuilder();
        sb37.append(APIConfig.API_URL);
        sb37.append("/Service/FolderFile/GetAllCheckedWithout");
        GETALLCHECKEDWITHOUT = sb37.toString();
        final StringBuilder sb38 = new StringBuilder();
        sb38.append(APIConfig.API_URL);
        sb38.append("/Service/FolderFile/DeleteMulti");
        DELETEMULTI = sb38.toString();
        final StringBuilder sb39 = new StringBuilder();
        sb39.append(APIConfig.API_URL);
        sb39.append("/Service/FolderFile/ReNameAdd");
        RENAMEADD = sb39.toString();
        final StringBuilder sb40 = new StringBuilder();
        sb40.append(APIConfig.API_URL);
        sb40.append("/Service/GSGroup/List");
        GSGROUPLIST = sb40.toString();
        final StringBuilder sb41 = new StringBuilder();
        sb41.append(APIConfig.API_URL);
        sb41.append("/Service/Ppt/GuidePptList");
        GUIDEPPTLIST = sb41.toString();
        final StringBuilder sb42 = new StringBuilder();
        sb42.append(APIConfig.API_URL);
        sb42.append("/Service/Notice/WebView");
        NOTICEWEB = sb42.toString();
        final StringBuilder sb43 = new StringBuilder();
        sb43.append(APIConfig.API_URL);
        sb43.append("/Service/Notice/GetUnReadCount");
        GETUNREADCOUNT = sb43.toString();
        final StringBuilder sb44 = new StringBuilder();
        sb44.append(APIConfig.API_URL);
        sb44.append("/Service/Notice/GetList");
        GETLIST = sb44.toString();
        final StringBuilder sb45 = new StringBuilder();
        sb45.append(APIConfig.API_URL);
        sb45.append("/Service/Notice/ReadAll");
        READ_ALL = sb45.toString();
        final StringBuilder sb46 = new StringBuilder();
        sb46.append(APIConfig.API_URL);
        sb46.append("/Service/User/LogOff");
        LOGOFF = sb46.toString();
        final StringBuilder sb47 = new StringBuilder();
        sb47.append(APIConfig.API_URL);
        sb47.append("/Service/Content/WebView");
        XIEYILOGOFF = sb47.toString();
        final StringBuilder sb48 = new StringBuilder();
        sb48.append(APIConfig.KINGDRAW_DOC);
        sb48.append("/KingDraw_Handbook3.4/En/3.4\u7248\u672c\u65b0\u529f\u80fd\u4ecb\u7ecd.html");
        NEW_VERSION_EN = sb48.toString();
        final StringBuilder sb49 = new StringBuilder();
        sb49.append(APIConfig.KINGDRAW_DOC);
        sb49.append("/KingDraw_Handbook3.4/3.4\u7248\u672c\u65b0\u529f\u80fd\u4ecb\u7ecd.html");
        NEW_VERSION_ZH = sb49.toString();
        final StringBuilder sb50 = new StringBuilder();
        sb50.append(APIConfig.KINGDRAW_DOC);
        sb50.append("/KingDraw_Handbook2.5.0/list.html");
        HELP_ZH = sb50.toString();
        final StringBuilder sb51 = new StringBuilder();
        sb51.append(APIConfig.KINGDRAW_DOC);
        sb51.append("/KingDraw_Handbook2.5.0/en/list.html");
        HELP_EN = sb51.toString();
        final StringBuilder sb52 = new StringBuilder();
        sb52.append(APIConfig.API_URL);
        sb52.append("/Service/UserShare/Share");
        SHARE = sb52.toString();
        final StringBuilder sb53 = new StringBuilder();
        sb53.append(APIConfig.KINGDRAW_DOC);
        sb53.append("/KingDraw_Handbook3.0.0/format.html");
        FORMAT_ZH = sb53.toString();
        final StringBuilder sb54 = new StringBuilder();
        sb54.append(APIConfig.KINGDRAW_DOC);
        sb54.append("/KingDraw_Handbook3.0.0/en/format.html");
        FORMAT_EN = sb54.toString();
        final StringBuilder sb55 = new StringBuilder();
        sb55.append(APIConfig.IP_BAIKE);
        sb55.append("/Scripts/mobile/index.html");
        API_BK_HOME = sb55.toString();
        final StringBuilder sb56 = new StringBuilder();
        sb56.append(APIConfig.IP_BAIKE);
        sb56.append("/Scripts/mobile/list.html");
        API_BK_LIST = sb56.toString();
        final StringBuilder sb57 = new StringBuilder();
        sb57.append(APIConfig.NEW_IP_URL);
        sb57.append("/api/Settings/GetWhiteList");
        getWhiteList = sb57.toString();
        final StringBuilder sb58 = new StringBuilder();
        sb58.append(APIConfig.OCR_URL);
        sb58.append("/upload/UploadAppUnrecognisedImage");
        UPLOAD_APP_UNRECOGNISED_IMAGE = sb58.toString();
        final StringBuilder sb59 = new StringBuilder();
        sb59.append(APIConfig.API_URL);
        sb59.append("/Service/Update/CheckVersionIsNotAvailable");
        CHECK_VERSION_IS_NOT_AVAILABLE = sb59.toString();
        final StringBuilder sb60 = new StringBuilder();
        sb60.append(APIConfig.IP_BAIKE);
        sb60.append("/Api/Search");
        CAS_SEARCH = sb60.toString();
    }
}
